### PR TITLE
CMS Framework

### PR DESCRIPTION
**Pull request by vatsalparekh**
# Project Title
A CMS Framework for Colleges

## Abstract / Purpose
Creating a CMS like Framework with modular design, which can manage large number of users and groups with desired role base access controls. On top of this framework, we can build plug-able features which allow Colleges to collaborate more effectively.  

### Description
A CMS Framework with modular design, where we can plug more features as we want to on top of a standard Framework. CMS tool for Colleges, is one of the effective use of the framework, but should be extendable and plug-able by design.

In CMS Application for Colleges, we can think of features like Roll-call management, students/alumni data management, file sharing, or more custom features if one wants.  

Goals for 6 months:
- Requirement understanding and design planning
- Developing and evolving Standard users framework
- Building integration with the framework for use of Colleges
- Documentation and Tests

### Prior knowledge required
- [x] Python (Proficient)
- [x] Django (More the Beginner)
- [x] REST API (Proficient)
- [x] UI/UX (Basic)

### Tools & Technology
- [x] Python
- [x] Django
- [x] Template libraries and UI frameworks (bootstrap)

Reference | Links
------ | ------
Django | [Django](https://www.djangoproject.com/)
WordPress (for design reference) | [WordPress](http://wordpress.org)

#### Are you willing to be the mentor to this problem statement *Technically* or *Non-Technically* ?
- Both

#### Github User Id:
@vatsalparekh

### CODE REVIEW

**Comment by amolkahat** [comment]
@vatsalparekh Please take look in to the PHP, Drupal, and other frameworks.

**Comment by rabajaj0509** [comment]
@vatsalparekh thanks for the problem statement :+1: if we propose this topic to a college or a group of students, will you be able to build the system with them? 

Also, have you built a similar system? is it on GitHub?

**Comment by vatsalparekh** [comment]
@rahulbajaj0509 I would like to re-work on the idea, but yes I can help with django and python related projects.

**Comment by rabajaj0509** [comment]
@vatsalparekh  my entire intention of asking was if you have or would like to work on such a project then we are good to go :)

**Comment by vatsalparekh** [comment]
always in @rahulbajaj0509 :)

**Comment by rabajaj0509** [comment]
awesome !
Thanks @vatsalparekh

**Pull request merged**
