### PR TITLE
miniSat

### PR DESCRIPTION
**Pull request by ntkathole**
# miniSat

## Abstract / Purpose 
A single, centralised web-based solution to monitor and configure systems, manage content (package management) and provision host with different provider. Host systems can fetch content from application. User can create and manage different versions of this content and apply them to specific systems.

### Pre-requisites:
Minimum 2 machines having 250Gb storage and 4Gb RAM each.
Set up background infrastructure of libvirt, docker to provision hosts.
Set up ldap server having users created.

### Requirements :
- As a user, I should be able to login application with ldap authentication on application.
- As a user, I should be able to provision host with different provider such as libvirt, docker container etc.
- As a user, I should be able to configure network and storage, select type of provider, type of operating system and contents. 
- As a user, I should be able to register already provisioned host within network to application.
(Existing machine having already installed operating system can fetch packages from server application)
- As a user, I should be able to enable services such as DHCP, DNS, TFTP, etc.
- As a user, I should be able to sync content from application to host.
- As a user, I should be able to get system health.

### Design 

<a href="https://imgbb.com/">final</a>

### High level goals :
    Application should be able to perform 

- Package management 

- Provisioning

### Level :
        Intermediate 

### Technical Terminologies:
        LibVirt, python, Web frameworks, Docker, etc.
        ( Note : Feel free to choose any open source technology )

### Project Planning:

Month 1:
1. Create abstract, define objective, information gathering and system architecture.
2. Understand virtualization concepts and configurations.
3. Gather Tools and Technology.
4. Create project on Github.

Month 2:
1. Project Design
2. Use cases and project specifications

Month 3:
1. Coding and implementation

Month 4:
    1. Coding and implementation

Month 5:
1. Testing
2. Create tests for application using pytest framework.

Month 6:
1. Contribution to open source projects such as foreman, katello, robottelo.
2. Bug raised on Redmine(http://www.redmine.org).

### Outcomes:
1. To understand infrastructure and virtualization concepts.
2. To learn automation.
3. To learn github and pytest framework.
4. Get familiar with foreman open source project and Red Hat Satellite product.

### References
https://theforeman.org
http://projects.theforeman.org/issues
https://www.redhat.com/en/technologies/management/satellite

### Github User Id:
        https://github.com/ntkathole

### CODE REVIEW

**Comment by amolkahat** [comment]
- Add more description

**Comment by yadneshk** [comment]
* Nikhil apart from libvirt, are we supposed to spawn VMs using docker also??

**Comment by ntkathole** [comment]
@yadneshk creating container using docker.

**Comment by rabajaj0509** [comment]
I think this problem statement is workable and practical at the same time :)
Thanks @ntkathole

**Pull request merged**
